create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  nickname text,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  user_id bigint references public.users(id) on delete set null,
  title text not null,
  content text not null,
  image_url text,
  tags text[] not null default '{}',
  likes_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.article_likes (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  ip_address text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists articles_category_created_idx on public.articles(category_id, created_at desc);
create index if not exists articles_created_idx on public.articles(created_at desc);
create index if not exists article_likes_article_idx on public.article_likes(article_id);

create or replace function public.increment_article_likes(
  target_article_id bigint,
  visitor_ip text default 'unknown',
  visitor_agent text default null
)
returns integer
language plpgsql
security definer
as $$
declare
  new_count integer;
begin
  insert into public.article_likes(article_id, ip_address, user_agent)
  values (target_article_id, visitor_ip, visitor_agent);

  update public.articles
  set likes_count = likes_count + 1
  where id = target_article_id
  returning likes_count into new_count;

  return coalesce(new_count, 0);
end;
$$;

alter table public.users enable row level security;
alter table public.categories enable row level security;
alter table public.articles enable row level security;
alter table public.article_likes enable row level security;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories" on public.categories
  for select using (true);

drop policy if exists "Public can read articles" on public.articles;
create policy "Public can read articles" on public.articles
  for select using (true);

insert into public.categories(name)
values ('AI 工具'), ('梗圖收藏'), ('DM 靈感')
on conflict do nothing;

-- Default login: admin / 671230
-- Change this password immediately after first deployment.
insert into public.users(username, nickname, password_hash)
values (
  'admin',
  '管理者',
  '$2a$12$5bI9xTFnYrbT9vLQSNGpUemyE7WDCHVr4DlSXn1mWT50/fbE3ztg2'
)
on conflict (username) do nothing;

grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.increment_article_likes(bigint, text, text) to service_role;

grant usage on schema public to anon;
grant select on public.categories, public.articles to anon;
grant execute on function public.increment_article_likes(bigint, text, text) to anon;
